Working prototype of Dustrak file join in Collection Creation
openoakland/woeip pull request #181
Opened 2020-02-12 05:04 UTC by jayqi

---
name: Pull Request
about: Request merging changes into the code base
title: 'Working prototype of Dustrak file join in Collection Creation'

---

## Checklist
- [ ] Add description
- [ ] Reference open issue pull request addresses
- [ ] Pass functional tests
  - complete on the local machine with `make local.shell` `make test`
- [ ] Request code review
  - Please allow **36 hours** from opening a pull request before merging a pull request- even if it has already recieved an approving review.
- [ ] Address comments on code and resolve requested changes
- [ ] Merge own code

## Description
Issue: #154

This PR implements a barebones working prototype of an end-to-end data upload using the `/collection` POST endpoint. This simply adds additional logic to `CollectionSerializer` to run `load_dustrak` and `load_gps` on the two uploaded files, and then join the two dataframes and save the result.

Some additional salient changes for all of this to work:
- Add `id` fields to `CollectionSerializer` and `PollutantSerializer`
- Add a FK field to `CollectionSerializer` to a `Pollutant` object. This is necessary because `save_dustrak` needs a pollutant. 

Some potential areas of improvement:
- Right now the logic looks for substrings `dustrak` and `gps` in the file name to guess which file is which. Is this too fragile/restrictive?
- Right now timezone is hard-coded to `America/Los_Angeles`. Do we want to add this to the endpoint instead?
- I put in some basic exception handling that writes out some messages and any exception text. Should this be more structured and/or more detailed? 

Below is a sample payload. The data is string-ified from the two sample files in our unit tests. 

```
{
  "starts_at": "2020-02-12T03:28:48.164Z",
  "ends_at": "2020-02-12T03:28:48.164Z",
  "upload_files": [
{"file_name": "gps_file.log",
                     "file_data": "$ADVER,3080,2.3\n$GPWPL,3748.1890,N,12217.6673,W,00001*63\n$ADPMB,5,0\n$GPRMC,192152.825,A,3748.1890,N,12217.6673,W,0.15,313.50,060814,,,A*7F\n$GPGGA,192153.825,3748.1883,N,12217.6676,W,1,04,3.4,20.9,M,-25.1,M,,0000*53\n$GPGSA,A,3,26,06,30,15,,,,,,,,,4.7,3.4,3.3*33\n$GPGSV,3,1,12,06,36,153,38,15,23,252,31,26,20,211,34,30,08,141,32*78\n$GPGSV,3,2,12,17,61,040,,04,43,087,33,24,37,311,,28,32,078,*77\n$GPGSV,3,3,12,09,16,146,,02,14,182,38,12,12,287,,01,08,036,*71\n$GPRMC,192153.825,A,3748.1883,N,12217.6676,W,0.32,68.69,060814,,,A*49\n$GPVTG,68.69,T,,M,0.32,N,0.6,K,A*3B\n$GPGGA,192154.825,3748.1875,N,12217.6679,W,1,04,3.4,20.5,M,-25.1,M,,0000*5E\n$GPGSA,A,3,26,06,30,15,,,,,,,,,4.7,3.4,3.3*33\n$GPRMC,192154.825,A,3748.1875,N,12217.6679,W,0.25,67.73,060814,,,A*4A\n$GPVTG,67.73,T,,M,0.25,N,0.5,K,A*3A\n$GPGGA,192155.000,3748.1871,N,12217.6679,W,1,04,3.4,20.5,M,-25.1,M,,0000*54\n$GPGSA,A,3,26,06,30,15,,,,,,,,,4.7,3.4,3.3*33\n$GPRMC,192155.000,A,3748.1871,N,12217.6679,W,0.30,146.40,060814,,,A*76\n$GPVTG,146.40,T,,M,0.30,N,0.5,K,A*0C\n$GPGGA,192156.000,3748.1860,N,12217.6675,W,1,04,3.4,20.8,M,-25.1,M,,0000*56\n$GPGSA,A,3,26,06,30,15,,,,,,,,,4.7,3.4,3.3*33\n$GPRMC,192156.000,A,3748.1860,N,12217.6675,W,0.88,138.81,060814,,,A*7E\n$GPVTG,138.81,T,,M,0.88,N,1.6,K,A*09\n$GPGGA,192157.000,3748.1816,N,12217.6674,W,1,04,3.4,21.4,M,-25.1,M,,0000*5A\n$GPGSA,A,3,26,06,30,15,,,,,,,,,4.7,3.4,3.3*33\n$GPRMC,192157.000,A,3748.1816,N,12217.6674,W,1.64,161.55,060814,,,A*79\n$GPVTG,161.55,T,,M,1.64,N,3.0,K,A*0B\n$GPGGA,192158.000,3748.1785,N,12217.6679,W,1,04,3.4,21.4,M,-25.1,M,,0000*5D\n$GPGSA,A,3,26,06,30,15,,,,,,,,,4.7,3.4,3.3*33\n$GPGSV,3,1,12,06,36,153,38,15,23,252,20,26,20,211,28,30,08,141,36*71\n$GPGSV,3,2,12,17,61,040,35,04,43,087,37,24,37,311,,28,32,078,38*7E\n$GPGSV,3,3,12,09,16,146,,02,14,182,33,12,12,287,18,01,08,036,*73\n$GPVTG,185.56,T,,M,2.80,N,5.2,K,A*0F\n$GPGGA,192159.000,3748.1788,N,12217.6678,W,1,04,3.4,21.3,M,-25.1,M,,0000*57\n$GPGSA,A,3,26,06,30,15,,,,,,,,,4.7,3.4,3.3*33\n$GPRMC,192159.000,A,3748.1788,N,12217.6678,W,2.40,183.27,060814,,,A*7F\n$GPVTG,183.27,T,,M,2.40,N,4.5,K,A*05\n$GPGGA,192200.000,3748.1775,N,12217.6678,W,1,04,3.4,21.4,M,-25.1,M,,0000*5D\n$GPGSA,A,3,26,06,30,15,,,,,,,,,4.7,3.4,3.3*33\n$GPRMC,192200.000,A,3748.1775,N,12217.6678,W,2.58,177.24,060814,,,A*73\n$GPVTG,177.24,T,,M,2.58,N,4.8,K,A*09\n$GPGGA,192201.000,3748.1764,N,12217.6679,W,1,03,23.2,21.3,M,-25.1,M,,0000*69\n$GPGSA,A,2,26,06,30,,,,,,,,,,23.2,23.2,1.0*33\n$GPRMC,192201.000,A,3748.1764,N,12217.6679,W,2.67,177.15,060814,,,A*7D\n$GPVTG,177.15,T,,M,2.67,N,5.0,K,N*01\n$GPGGA,192202.000,3748.1754,N,12217.6680,W,1,03,23.2,21.3,M,-25.1,M,,0000*6F\n$GPGSA,A,2,26,06,30,,,,,,,,,,23.2,23.2,1.0*33\n$GPRMC,192202.000,A,3748.1754,N,12217.6680,W,2.76,178.63,060814,,,A*75\n$GPVTG,178.63,T,,M,2.76,N,5.1,K,N*0E\n$GPGGA,192203.000,3748.1737,N,12217.6679,W,1,04,3.4,21.5,M,-25.1,M,,0000*58\n$GPGSA,A,3,26,06,30,15,,,,,,,,,4.7,3.4,3.3*33\n$GPGSV,3,1,12,06,36,153,33,15,23,252,17,26,20,211,28,30,08,141,27*7E\n$GPGSV,3,2,12,17,61,040,19,04,43,087,25,24,37,311,,28,32,078,21*7B\n$GPGSV,3,3,12,09,16,146,,02,14,182,33,12,12,287,18,01,08,036,*73\n$GPRMC,192203.000,A,3748.1737,N,12217.6679,W,2.71,185.20,060814,,,A*75\n$GPVTG,185.20,T,,M,2.71,N,5.0,K,A*02\n$GPGGA,192204.000,3748.1740,N,12217.6682,W,1,04,3.4,21.2,M,-25.1,M,,0000*5C\n$GPGSA,A,3,26,06,30,15,,,,,,,,,4.7,3.4,3.3*33\n$GPRMC,192204.000,A,3748.1740,N,12217.6682,W,1.69,183.58,060814,,,A*75\n$GPVTG,183.58,T,,M,1.69,N,3.1,K,A*06\n$GPGGA,192205.000,3748.1747,N,12217.6685,W,1,04,3.4,20.8,M,-25.1,M,,0000*56\n$GPGSA,A,3,26,06,30,15,,,,,,,,,4.7,3.4,3.3*33\n$GPRMC,192205.000,A,3748.1747,N,12217.6685,W,1.22,187.94,060814,,,A*7F\n$GPVTG,187.94,T,,M,1.22,N,2.3,K,A*0E\n$GPGGA,192206.000,3748.1753,N,12217.6689,W,1,04,3.4,18.8,M,-25.1,M,,0000*57\n$GPGSA,A,3,26,06,30,15,,,,,,,,,4.7,3.4,3.3*33\n$GPRMC,192206.000,A,3748.1753,N,12217.6689,W,0.71,197.02,060814,,,A*7C\n$GPVTG,197.02,T,,M,0.71,N,1.3,K,A*04\n$GPGGA,192207.000,3748.1761,N,12217.6696,W,1,04,3.4,18.3,M,-25.1,M,,0000*52\n$GPGSA,A,3,26,06,30,15,,,,,,,,,4.7,3.4,3.3*33\n$GPRMC,192207.000,A,3748.1761,N,12217.6696,W,1.39,224.06,060814,,,A*70\n$GPVTG,224.06,T,,M,1.39,N,2.6,K,A*00\n$GPGGA,192208.000,3748.1769,N,12217.6700,W,1,04,3.4,17.6,M,-25.1,M,,0000*51\n$GPGSA,A,3,26,06,30,15,,,,,,,,,4.7,3.4,3.3*33\n$GPGSV,3,1,12,06,36,153,30,15,23,252,31,26,20,211,33,30,08,141,30*75\n$GPGSV,3,2,12,17,61,040,21,04,43,087,22,24,37,311,,28,32,078,24*72\n$GPGSV,3,3,12,09,16,146,,02,14,182,27,12,12,287,21,01,08,036,*7C\n$GPRMC,192208.000,A,3748.1769,N,12217.6700,W,1.23,199.85,060814,,,A*7C\n$GPVTG,199.85,T,,M,1.23,N,2.3,K,A*00\n$GPGGA,192209.000,3748.1773,N,12217.6702,W,1,04,3.4,17.3,M,-25.1,M,,0000*5C\n$GPGSA,A,3,26,06,30,15,,,,,,,,,4.7,3.4,3.3*33\n$GPRMC,192209.000,A,3748.1773,N,12217.6702,W,1.38,201.77,060814,,,A*71\n$GPVTG,201.77,T,,M,1.38,N,2.6,K,A*00\n$GPGGA,192210.000,3748.1775,N,12217.6705,W,1,04,3.4,17.2,M,-25.1,M,,0000*54\n$GPGSA,A,3,26,06,30,15,,,,,,,,,4.7,3.4,3.3*33\n$GPRMC,192210.000,A,3748.1775,N,12217.6705,W,1.43,213.24,060814,,,A*71\n$GPVTG,213.24,T,,M,1.43,N,2.6,K,A*09\n$GPGGA,192211.000,3748.1776,N,12217.6708,W,1,04,3.4,17.3,M,-25.1,M,,0000*5A\n$GPGSA,A,3,26,06,30,15,,,,,,,,,4.7,3.4,3.3*33\n$GPRMC,192211.000,A,3748.1776,N,12217.6708,W,1.07,210.53,060814,,,A*7D\n$GPVTG,210.53,T,,M,1.07,N,2.0,K,A*0C\n$GPGGA,192212.000,3748.1776,N,12217.6709,W,1,04,3.4,17.3,M,-25.1,M,,0000*58\n$GPGSA,A,3,26,06,30,15,,,,,,,,,4.7,3.4,3.3*33\n$GPRMC,192212.000,A,3748.1776,N,12217.6709,W,0.73,206.50,060814,,,A*79\n$GPVTG,206.50,T,,M,0.73,N,1.4,K,A*0D\n$GPGGA,192213.000,3748.1776,N,12217.6710,W,1,04,3.4,17.5,M,-25.1,M,,0000*57\n$GPGSA,A,3,26,06,30,15,,,,,,,,,4.7,3.4,3.3*33\n$GPGSV,3,1,12,06,36,153,28,15,23,252,31,26,20,211,36,30,08,141,36*7F\n$GPGSV,3,2,12,17,61,040,21,04,43,087,18,24,37,311,,28,32,078,24*7B\n$GPGSV,3,3,12,09,16,146,,02,14,182,28,12,12,287,21,01,08,036,*73\n$GPRMC,192213.000,A,3748.1776,N,12217.6710,W,0.48,202.55,060814,,,A*79\n$GPGGA,192214.000,3748.1776,N,12217.6708,W,1,04,3.4,19.5,M,-25.1,M,,0000*57\n$GPGSA,A,3,26,06,30,15,,,,,,,,,4.7,3.4,3.3*33\n$GPRMC,192214.000,A,3748.1776,N,12217.6 [...]

2020-02-19 03:26 UTC, jayqi commented
The Travis build is failing due to #183 for reasons unrelated to the changes in this PR. :(

2020-02-19 04:29 UTC, nbilenko requested changes
Great work! Some suggestions for checks and tests.

2020-02-19 04:29 UTC, nbilenko commented on api/woeip/apps/air_quality/serializers.py
> +            if "dustrak" in str(collection_file.file.path):
Suggestion:
`if "dustrak" in str(collection_file.file.path.lower()):`
for naming flexibility.

2020-02-19 04:29 UTC, nbilenko commented on api/woeip/apps/air_quality/serializers.py
> +            elif "gps" in str(collection_file.file.path):
Suggestion:
`elif "gps" in str(collection_file.file.path.lower()):`
for naming flexibility.

2020-02-19 04:29 UTC, nbilenko commented on api/woeip/apps/air_quality/serializers.py
> +
Suggestion: check  that there is a single GPS and a single Dustrak file here before going through any data processing (instead of lines 115-133) so that no unnecessary processing is done:
```
errors = []
dustrak_error_message = (
               "Please upload a single valid file with 'dustrak' in the filename. "
               )
gps_error_message = (
                "Please upload a single valid file with 'gps' in the filename."
            )
dustrak_list = [f for f in collection_files if "dustrak" in f.file.path.lower()]
gps_list = [f for f in collection_files if "gps" in f.file.path.lower()]
if len(dustrak_list) != 1:
    errors.append(dustrak_error_message)
if len(gps_list) != 1:
    errors.append(gps_error_message)
if len(errors) > 0:
    raise exceptions.ValidationError(detail=errors)
```
And then to avoid the `for` loops:
```
dustrak_file = dustrak_list[0]
gps_file = gps_list[0]
...
try:
    dustrak_file = collection_file
    dustrak_metadata, dustrak_df = load_dustrak(
                        dustrak_file.file.path, tz="America/Los_Angeles"
                    )
except Exception as e:
    dustrak_exception = e
```

2020-02-19 04:29 UTC, nbilenko commented on api/woeip/apps/air_quality/serializers.py
> +                gpserror_message += repr(gps_exception)
typo: `gps_error_message`

2020-02-19 04:29 UTC, nbilenko commented on api/woeip/apps/air_quality/serializers.py
> +                except Exception:
*`except Exception as e:`

2020-02-19 04:29 UTC, nbilenko commented on api/woeip/apps/air_quality/tests/test_api.py
Suggested new tests here:
```
    def test_create_collection_missing_gps(self):
        """Tests collection create method."""
        starts_at = datetime.datetime(2019, 1, 1, 10, 15)
        ends_at = datetime.datetime(2019, 1, 1, 14, 15)

        with open(GPS_PATH) as f:
            gps_file_data = f.read()

        with open(DUSTRAK_PATH) as f:
            dustrak_file_data = f.read()

        pollutant = factories.PollutantFactory()

        data = {
            "upload_files": [
                {"file_name": "bad_file.log", "file_data": gps_file_data},
                {"file_name": "dustrak_file.csv", "file_data": dustrak_file_data},
            ],
            "starts_at": starts_at,
            "ends_at": ends_at,
            "pollutant": pollutant.pk,
        }
        response = self.client.post("/collection", data, format="json")
        print(response.content)
        assert response.status_code == 400
        assert response.content.startswith(b'["Please upload')

    def test_create_collection_missing_dustrak(self):
        """Tests collection create method."""
        starts_at = datetime.datetime(2019, 1, 1, 10, 15)
        ends_at = datetime.datetime(2019, 1, 1, 14, 15)

        with open(GPS_PATH) as f:
            gps_file_data = f.read()

        with open(DUSTRAK_PATH) as f:
            dustrak_file_data = f.read()

        pollutant = factories.PollutantFactory()

        data = {
            "upload_files": [
                {"file_name": "gps_file.log", "file_data": gps_file_data},
                {"file_name": "bad_file.csv", "file_data": dustrak_file_data},
            ],
            "starts_at": starts_at,
            "ends_at": ends_at,
            "pollutant": pollutant.pk,
        }
        response = self.client.post("/collection", data, format="json")
        print(response.content)
        assert response.status_code == 400
        assert response.content.startswith(b'["Please upload')

    def test_create_collection_wrong_number(self):
        """Tests collection create method."""
        starts_at = datetime.datetime(2019, 1, 1, 10, 15)
        ends_at = datetime.datetime(2019, 1, 1, 14, 15)

        with open(GPS_PATH) as f:
            gps_file_data = f.read()

        with open(DUSTRAK_PATH) as f:
            dustrak_file_data = f.read()

        pollutant = factories.PollutantFactory()

        data = {
            "upload_files": [
                {"file_name": "random_file.log", "file_data": gps_file_data},
                {"file_name": "dustrak_file.csv", "file_data": dustrak_file_data},
                {"file_name": "dustrak_file1.csv", "file_data": dustrak_file_data},
            ],
            "starts_at": starts_at,
            "ends_at": ends_at,
            "pollutant": pollutant.pk,
        }
        response = self.client.post("/collection", data, format="json")
        print(response.content)
        assert response.status_code == 400
        assert response.content.startswith(b'["Please upload')
```

2020-02-26 03:28 UTC, nbilenko commented on api/woeip/apps/air_quality/serializers.py
> +
Found error: the line `dustrak_file = collection_file` should not be there

2020-02-26 03:35 UTC, nbilenko approved these changes
LGTM!! Awesome work!

2020-02-26 03:41 UTC, jayqi commented on api/woeip/apps/air_quality/tests/test_api.py
I added these tests.

2020-02-26 05:02 UTC, jayqi commented
Tests are passing. Build is failing due to #183.

2020-02-26 05:02 UTC, merged