Added choices attribute to unit field under sensor
openoakland/woeip pull request #24
Opened 2019-02-03 19:44 UTC by Ethan-bradley

This fixes issue #13, which was to add a dropdown field for the measurements section in the sensor field.

2019-02-03 20:03 UTC, r-b-g-b commented
Thanks Ethan! The Travis error says that a database migration file is missing. If this change requires a database migration, could you commit that as well?

2019-02-03 20:41 UTC, TangoYankee requested changes
Before we perform a full review, please address the failing tests.
* `Makefile:43: recipe for target 'quality' failed
make: *** [quality] Error 1`
* `Migration files are missing. Please run the makemigrations management command, and commit the migrations.
Makefile:53: recipe for target 'detect_missing_migrations' failed`

2019-02-03 21:23 UTC, r-b-g-b requested changes

2019-02-03 21:23 UTC, r-b-g-b commented on woeip/apps/air_quality/models.py
> +    Unit_Choices = (('mg/m3','mg/m3'),('ppm','ppm'),('g/m3','g/m3'),('PM10','PM10'),('PM2.5','PM2.5'),('ug/m3','ug/m3'))
Let's use PEP8 and flake8 style conventions:
- ``Unit_Choices`` --> ``unit_choices`` (https://www.python.org/dev/peps/pep-0008/#function-and-variable-names)
- spaces after commas (https://lintlyci.github.io/Flake8Rules/rules/E231.html)

We can also use unicode characters, so ``u`` --> ``μ``

2019-02-06 04:22 UTC, TangoYankee commented
Change PR to eb/choices_attributes

2019-02-06 04:22 UTC, closed without merging