Added lat/lon to unit_choices dropdown
openoakland/woeip pull request #30
Opened 2019-02-10 01:13 UTC by Ethan-bradley

This pull request added the latitude/longitude as an option in the unit_choices dropdown.

2019-02-10 01:55 UTC, TangoYankee approved these changes

2019-02-10 19:44 UTC, r-b-g-b requested changes

2019-02-10 19:44 UTC, r-b-g-b commented on woeip/apps/air_quality/models.py
> +                    ('μg/m3', 'μg/m3'), ('latitude/longitude', 'latitude/longitude'))
Can I suggest naming it ``('latlon', 'Latitude/Longitude')``. ``latlon`` would have it match the field name: ``Data.latlon``

2019-02-10 19:44 UTC, r-b-g-b commented on woeip/apps/air_quality/models.py
> +                    ('μg/m3', 'μg/m3'), ('latitude/longitude', 'latitude/longitude'))
Also ``('PM2.5', 'PM2.5'), ('μg/m3', 'μg/m3'), ('latlon', 'Latitude/Longitude'))`` can all be on one line (120 character line limit)

2019-02-10 19:44 UTC, r-b-g-b commented on woeip/apps/air_quality/models.py
> +                    ('μg/m3', 'μg/m3'), ('latitude/longitude', 'latlong'))
I think the order should be flipped: first element is how it's stored in the db, second is a more human-readable version. So ``('latlon', 'Latitude/Longitude')``

2019-02-11 01:04 UTC, TangoYankee commented on woeip/apps/air_quality/models.py
> +                    ('μg/m3', 'μg/m3'), ('latitude/longitude', 'latlong'))
[correct](https://docs.djangoproject.com/en/2.1/ref/models/fields/#choices)

2019-02-13 17:37 UTC, r-b-g-b approved these changes

2019-02-13 17:43 UTC, merged