add skeleton sessionmap page
openoakland/woeip pull request #65
Opened 2019-03-13 08:28 UTC by nbilenko

## Description
Issue: https://github.com/openoakland/woeip/issues/64

Skeleton sessionmap page (according to wireframe 9 in https://trello.com/c/f81CfYp8/35-document-v2-ui-improvements-for-implementation), with some placeholder properties (marked with TODOs) and placeholder map section.

2019-03-13 22:10 UTC, TangoYankee commented on woeip/templates/session.html
> +<style>
CSS Should be in a dedicated file

2019-03-14 01:05 UTC, TangoYankee requested changes
Fix linting issues and pass Travis checks, [before requesting code review](https://github.com/openoakland/woeip/blob/master/.github/contributing.md#pull-requests). Create issues for any `TODO` or `unused import` that you would like to track.

Yeah, they're just linting issues. But, if we start choosing to ignore small failures, we might end up missing a big failure.

2019-03-14 03:30 UTC, nbilenko commented
> Fix linting issues and pass Travis checks, [before requesting code review](https://github.com/openoakland/woeip/blob/master/.github/contributing.md#pull-requests). Create issues for any `TODO` or `unused import` that you would like to track.
> 
> Yeah, they're just linting issues. But, if we start choosing to ignore small failures, we might end up missing a big failure.

Yes I realize I should've run `make quality` before submitting, sorry about that.

2019-03-14 15:39 UTC, TangoYankee commented
> Just to clarify, are we not allowing any `TODO` in the code? Currently the linting fails if there are any. This isn't ideal for WIP pull requests.

If we've planned the code in the `Issue`, there shouldn't be a need for `TODO` in a Pull Request. If you'd like to argue in favor of allowing `TODO`, open an `Issue`.

2019-03-18 19:42 UTC, nbilenko commented
> > Just to clarify, are we not allowing any `TODO` in the code? Currently the linting fails if there are any. This isn't ideal for WIP pull requests.
> 
> If we've planned the code in the `Issue`, there shouldn't be a need for `TODO` in a Pull Request. If you'd like to argue in favor of allowing `TODO`, open an `Issue`.

Ok, I can remove TODOs - I was just confirming that's the intended workflow. I was using TODOs to flag the placeholder parts of the code to be fleshed out as part of the same issue which wouldn't really warrant new issues but are dependent on other work (e.g. separating out static files, since it seems we haven't established a method for handling those yet; or querying for device name since it wasn't clear how we plan to distinguish the air quality one). But I can just keep track of these items via comments.

2019-05-22 02:51 UTC, theecrit commented
Blocked until associated issue is more fully defined.

2019-05-22 16:33 UTC, theecrit commented
Blocked by #64 requiring greater detail.

2019-09-18 20:16 UTC, nbilenko commented
Closing due to move to REST framework.

2019-09-18 20:16 UTC, closed without merging