Organize technical docs
openoakland/woeip pull request #82
Opened 2019-04-03 02:22 UTC by r-b-g-b

---
name: Organize technical docs
about: Organizing technical docs
title: ''
labels: ''
reviewers: ''

---

## 
- [ ] Add description
- [ ] Reference open issue pull request addresses
- [ ] Pass linting check
  - complete on the local machine with `make local.shell` `make quality`
- [ ] Pass functional tests
  - complete on the local machine with `make local.shell` `make test`
- [ ] Request code review
  - Please allow **36 hours** from opening a pull request before merging a pull request- even if it has already recieved an approving review.
- [ ] Address comments on code and resolve requested changes
- [ ] Merge own code

## Description
Issue: #62 

Move some technical docs to contributing.md and details about deployment to the [wiki](https://github.com/openoakland/woeip/wiki/Deployment).

2019-04-07 19:16 UTC, TangoYankee requested changes
The .rst Readme and the .md Contributing have different syntax for Hyperlinks.
In the Contributing doc, lines 39, 47, and 61 should change to Markdown hypertext formatting.

2019-04-08 00:31 UTC, r-b-g-b commented
Whoops should have caught those. I used this to make sure things render properly this time https://stackedit.io

2019-04-08 16:09 UTC, TangoYankee commented on .github/contributing.md
> +If you would prefer not to use Docker, you also be run the project directly on your machine using [pipenv](https://pipenv.readthedocs.io/en/latest/>). If you develop in this manner, you will be respo
The carrot at the end of the pipenv link redirects it to a non-existent page

2019-04-09 13:48 UTC, TangoYankee approved these changes

2019-04-09 16:20 UTC, merged