Signin page styling
openoakland/woeip pull request #87
Opened 2019-04-14 05:27 UTC by TangoYankee

## Checklist
- [x] Add description
- [x] Reference open issue pull request addresses
- [ ] Pass linting check
  - complete on the local machine with `make local.shell` `make quality`
- [x] Pass functional tests
  - complete on the local machine with `make local.shell` `make test`
- [x] Request code review
  - Please allow **36 hours** from opening a pull request before merging a pull request- even if it has already recieved an approving review.
- [ ] Address comments on code and resolve requested changes
- [ ] Merge own code

## Description
Issue: #71 

Responsive sizing of signin form, text to give users context, password toggle, email to request account.

2019-04-14 19:36 UTC, theecrit commented
See my comment on #71, please and thanks!

2019-04-17 03:00 UTC, nbilenko requested changes
For the h1/button/general element styling, does that need to be localized? It seems like the style can be general across the site.

2019-04-17 03:06 UTC, TangoYankee commented
> For the h1/button/general element styling, does that need to be localized? It seems like the style can be general across the site.

@theecrit This is a question of implementing your design. Do you want the links in the navigation bar to have their style extended to all buttons in the site?

2019-04-19 20:14 UTC, theecrit commented
Hi all, sorry for the delay. I'm working on figuring out how to get the latest build on my machine so I can see where we're at, but to try and answer the questions above:

> For the h1/button/general element styling, does that need to be localized? It seems like the style can be general across the site.

Yes, we probably want it generalized into a site-wide style guide. Of course, we don't have one yet but I created a [Trello card for it](https://github.com/drnikki/open-demographics/). For now, what specifics do you need from me to unblock this? Type styles and button styles?


> Do you want the links in the navigation bar to have their style extended to all buttons in the site?

Probably not. Navigation menu should be styled differently than action buttons. Of course, nav links should be styled consistently across the site (i.e. from page to page).

2019-04-19 20:18 UTC, theecrit commented
For now, how about we use the "[button-style-alternative](https://style.codeforamerica.org/)" style for primary buttons, and "button-style-subtle" for secondary buttons?

2019-04-20 03:06 UTC, TangoYankee commented
Upon rereading Natalia's comment, I think I misinterpreted the part to which see was referring. 

The question really seems to be whether to apply styles only to the current page, or extend them across the site to all elements with those tags. @nbilenko I want to default to localizing styling elements. This reduces the chance of unintentionally affecting another component.

For the CfA button styling guide, I'll implement the wireframe styling to the best of my ability. Below is the current iteration. On hover, the Signin form button turns black with white text. The right side links of the nav bar turn green. @theecrit, If you'd like to change them to the CfA styling, update the wireframes and I'll update the design.

![WOEIP Signin](https://user-images.githubusercontent.com/11068062/56450918-d7d70c00-62dd-11e9-80be-6d9074b687a6.png)

2019-04-20 03:29 UTC, theecrit commented
A couple of things:

I’d really advise against localizing styling. Style guided and design systems exist for a reason, and trying to update every single instance of a given style should a change be needed is not tenable. Let’s come up with a better solution. Unless I’m misunderstanding the questions, as well. 

Re: wireframe updates. I’d like us to practice uncoupling wireframes from redlines (pixel-specific visial design). Again, it’s about finding the path of least resistance balanced with best practice: the visual design styles should remain independent of content. The wireframes are intended to communicate content, hierarchy, relative layout, and in some cases, behavior. Visual design styles (e.g. css) need not be (and shouldn’t be) tied to wires, or we’ll add an additional layer of documentation labor that will be prohibitive to shipping. That’s why design systems like the CfA style guide exist; so developers can apply consistent styling without needing redlines. I’m happy to specify which styles should applied to specific elements in the wires, but I’m not going to be able to skin the site as we go. Of course, maybe that’s what you meant in the first place? 

Thanks!
J

2019-04-20 15:29 UTC, TangoYankee commented
It sounds like we're identifying a few differing assumptions. They're leading to a few things we need to discuss, that are outside the scope of a Pull Request discussion.

1) Wireframing v Redlining
2) Style guidelines (Default Foundation or CfA)
3) Scoping preferences for custom styling
2) The placement of buttons in the navigation bar

2019-04-21 14:27 UTC, TangoYankee commented
See issue #92 for explanation and discussion of changes

2019-04-24 01:56 UTC, theecrit commented
The main outstanding issue I'm seeing right now (if I understand the implementation correctly) is that buttons as navigation are problematic for a number of reasons. The main one is that buttons should be used as a _control_ interaction, whereas navigation is about wayfinding via _links_. Best practice, as far as I understand it, is to use unordered lists and CSS styling for navigation menus. Examples:

- https://a11y-style-guide.com/style-guide/section-navigation.html#kssref-navigation-navigation-basic
- https://www.w3.org/WAI/tutorials/menus/structure/

2019-04-24 02:15 UTC, r-b-g-b approved these changes
Looks good to me!

2019-04-24 21:04 UTC, nbilenko approved these changes

2019-04-24 21:04 UTC, nbilenko commented on woeip/templates/registration/login.html
> +          <a href="mailto:woaq@openoakland.org">woaq@openoakland.org</a>
The email should probably be passed from the backend as a context variable, but that can happen in the future.

2019-04-25 03:23 UTC, merged